[build-system]
requires = ["setuptools>=40.8.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.8"
name = "thinkingface"
version = "0.1.0dev1"
dependencies = [
    "textual>=0.34"
]

[project.scripts]
thinkingface="main:main"
think="main:main"